name: ci
on:
  push:
    branches:
      - main

jobs:
  build-latest:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Store Package Version
        id: version
        run: |-
          result="$(grep version package.json | awk -F \" '{print $4}')";
          echo "::set-output name=result::${result}";

      - name: Store Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rahilp/ingress-dns
          tags: |
            type=sha
            type=semver,pattern={{version}},value=${{ steps.version.outputs.result }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.result }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
